#!/usr/bin/python
#
# Copyright (c) 2019 Sine Nomine Associates
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THE SOFTWARE IS PROVIDED 'AS IS' AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

from __future__ import print_function

import argparse
import os
import re
import sys
import string

try:
    # python3
    from configparser import ConfigParser
    from configparser import NoSectionError
    from configparser import NoOptionError
except ImportError:
    # python2
    from ConfigParser import SafeConfigParser as ConfigParser
    from ConfigParser import NoSectionError
    from ConfigParser import NoOptionError

verbose = False
dryrun = False

VERSION = '1.0'
DESC  = 'Install and remove sets of guests on a local hypervisor using cloud-init images.'
USAGE = '''\
virt-lab [<options>] <command> [<name>]

Commands:
  create <name>     create a set of guests
  destroy <name>    destroy a set of guests
  start <name>      start a set of guests
  stop <name>       shutdown a set of guests
  list              list guest sets
  help              show help
  version           show version
'''
DEFAULTS = {
    'key': '~/.ssh/id_rsa.pub',
    'domain': 'example.com',
    'bridge': 'virbr0',
    'gateway': '192.168.122.1',
    'images': '3',
    'distro': 'centos7',
    'namefmt': '{lab}{guest:02d}',
    'vmdir': '~/virt/vms',
    'vardir': '~/virt/var',
}
TEMPLATES = ('postcreate', 'postdestroy')
PATHNAMES = ('key', 'vmdir', 'vardir')

def trace(msg):
    if verbose:
        sys.stdout.write('[trace]: %s\n' % msg)

def info(msg):
    sys.stdout.write('[info]: %s\n' % msg)

def warn(msg):
    sys.stdout.write('[warn]: %s\n' % msg)

def error(msg):
    sys.stderr.write('[error]: %s\n' % msg)

def die(msg):
    sys.stderr.write('[fatal]: %s\n' % msg)
    sys.exit(1)

def mkdirp(path):
    if not os.path.exists(path):
        os.makedirs(path)

def shellquote(s):
    """Return a shell-escaped string."""
    s = str(s)
    if not s:
        return "''"
    m = re.search(r'[^a-zA-Z0-9_:\-\./]', s)
    if m:
        s = "'" + s.replace("'", "'\"'\"'") + "'"
    return s

def run(args):
    """Run a command."""
    if isinstance(args, (list, tuple)):
        cmdline = ' '.join([shellquote(a) for a in args])
    else:
        cmdline = str(args)
    if dryrun:
        trace('Skipping: %s' % cmdline)
        return 0
    trace('Running: %s' % cmdline)
    rc = os.system(cmdline)
    return rc


class VirshError(Exception):
    pass

def virsh(command, *options):
    args = ['virsh', command]
    args.extend(list(options))
    cmd = ' '.join(args)
    pipe = os.popen(cmd + ' 2>&1')
    if not pipe:
        raise VirshError('Failed to run command: %s' % cmd)
    output = pipe.read()
    rc = pipe.close()
    if rc is not None and rc != 0:
        raise VirshError('Error while running command: %s, rc=%d' % (cmd, rc))
    return output


class VirtLabFormatter(string.Formatter):
    def __init__(self, lab):
        self.lab = lab

    def get_value(self, key, args, kwargs):
        return self.lab.get(key)


class VirtLabValues:

    def __init__(self, name, args):
        self.name = name
        self.lab = name # alias
        self.values = {}
        self.args = args
        self.config = None

    def guests(self):
        for i,image in enumerate(self.get_images()):
            name = self.namefmt.format(lab=self.name, guest=(i+1))
            yield VirtLabGuest(name, image, self)

    def __getattr__(self, name):
        return self.get(name)

    def get(self, name):
        if not name in self.values:
            self.values[name] = self.get_value(name)
        return self.values[name]

    def get_value(self, name):
        value = self.get_arg_value(name)
        if value is None:
            value = self.get_cfg_value(name)
        if value is None:
            value = DEFAULTS.get(name, None)
        if value is not None:
            if name in TEMPLATES:
                value = self.expand_string(value)
            if name in PATHNAMES:
                value = os.path.expanduser(value)
        return value

    def get_arg_value(self, name):
        return getattr(self.args, name, None)

    def get_cfg_value(self, name):
        value = None
        if self.config is None:
            self.config = ConfigParser()
            try:
                with open(self.args.config) as f:
                    self.config.readfp(f)
            except IOError as e:
                die('Unable to read config file %s.\n%s' % (self.args.config, e))
        try:
            value = self.config.get(self.name, name)
        except NoSectionError:
            die('Lab name not found in config file %s' % (self.args.config))
        except NoOptionError:
            pass
        return value

    def get_images(self):
        images = self.get('images')
        if hasattr(images, 'split'):
            images = images.split()
        for image in images:
            number,distro = self.parse_image_string(image)
            for i in range(number):
                yield distro

    def expand_string(self, value):
        formatter = VirtLabFormatter(self)
        value = formatter.format(value)
        return value

    def parse_image_string(self, image):
        trace('parse_image_string(): image=%s' % image)
        image = image.strip()
        m = re.search('^(\d+):(\w+)$', image)
        if m:
            number = int(m.group(1))
            distro = m.group(2)
            trace('number=%d, distro=%s' % (number,distro))
            return number, distro
        m = re.search('^(\d+)$', image)
        if m:
            number = int(m.group(1))
            distro = self.get('distro')
            trace('number=%d, distro=%s (default)' % (number,distro))
            return number, distro
        m = re.search('^(\w+)$', image)
        if m:
            number = 1
            distro = m.group(1)
            trace('number=%d (default), distro=%s' % (number,distro))
            return number, distro
        die('Unable to parse image string: "%s"' % image)


class VirtLabGuest:

    def __init__(self, name, image, lab):
        self.lab = lab
        self.name = name
        self.image = image
        self.dominfo = None

    def __getattr__(self, name):
        value = None
        if name == 'mac':
            value = self.get_mac()
            self.mac = value
        else:
            value = self.lab.get(name)
        return value

    def get_mac(self):
        if self.domain_exists():
            mac = self.domain_mac_addr()
        else:
            mac = self.read_var('mac')
        return mac

    def create(self):
        if self.domain_exists():
            warn('Skipping %s: domain already exists.' % self.name)
            return
        args = [
            'kvm-install-vm',
            'create',
            '-a',
            '-b', self.bridge,
            '-D', self.domain,
            '-k', self.key,
            '-t', self.image,
        ]
        if self.mac:
            args.extend(['-M', self.mac])
        args.append(self.name)
        info('creating guest %s with image %s' % (self.name, self.image))
        rc = run(args)
        if rc != 0:
            die('Failed to create guest %s' % (self.name))
        self.write_var('mac', self.domain_mac_addr())

    def destroy(self, purge):
        info('destroying guest %s' % self.name)
        run(['kvm-install-vm', 'remove', self.name])
        if purge:
            self.remove_var('mac')
            self.remove_vardir()

    def domain_info(self):
        if self.dominfo is None:
            dominfo = {}
            try:
                for line in virsh('dominfo', self.name).splitlines():
                    if not line:
                        continue
                    key,value = line.split(':', 1)
                    key = key.strip()
                    value = value.strip()
                    dominfo[key] = value
            except VirshError:
                return None
            self.dominfo = dominfo
        return self.dominfo

    def domain_exists(self):
        """Return True if domain exists."""
        return self.domain_info() is not None

    def domain_running(self):
        """Return True if domain is running."""
        return self.domain_exists() and self.domain_info()['State'] == 'running'

    def domain_start(self):
        if not self.domain_exists():
            error('Domain %s does not exist.' % self.name)
            return
        if self.domain_running():
            trace('Skipping start; domain %s is already running.' % self.name)
            return
        trace('Starting domain %s' % self.name)
        try:
            output = virsh('start', self.name)
            info(output.strip())
        except VirshError as e:
            error('Failed to start %s' % self.name)

    def domain_stop(self):
        if not self.domain_exists():
            trace('Skipping stop; domain %s does not exist' % self.name)
            return
        if not self.domain_running():
            trace('Skipping stop; domain %s is not running' % self.name)
            return
        trace('Stopping domain %s' % self.name)
        try:
            output = virsh('shutdown', self.name)
            info(output.strip())
        except VirshError as e:
            error('Failed to stop %s' % self.name)

    def domain_mac_addr(self):
        """Return the first mac address in the domain definition, if one."""
        try:
            text = virsh('dumpxml', self.name)
            for line in text.splitlines():
                m = re.search(r"<mac address='([0-9a-fA-F:]+)'/>", line)
                if m:
                    mac = m.group(1)
                    trace('guest %s has mac %s' % (self.name, mac))
                    return m.group(1)
        except VirshError:
            pass
        trace('guest %s: mac not found' % self.name)
        return None

    def read_var(self, name):
        value = None
        try:
            path = os.path.join(self.vardir, self.name, name)
            with open(path) as f:
                value = f.read().strip()
        except Exception as e:
            pass
        return value

    def write_var(self, name, value):
        if value is None:
            return
        path = os.path.join(self.vardir, self.name, name)
        mkdirp(os.path.dirname(path))
        with open(path, 'w') as f:
            f.write('%s\n' % value)

    def remove_var(self, name):
        path = os.path.join(self.vardir, self.name, name)
        try:
            os.unlink(path)
        except:
            pass

    def remove_vardir(self):
        path = os.path.join(self.vardir, self.name)
        try:
            os.rmdir(path)
        except:
            pass


class VirtLab:

    def __init__(self):
        self.command = ''
        self.args = argparse.Namespace(
            verbose=False,
            dryrun=False,
            purge=False,
            config=os.path.expanduser('~/virt-lab.cfg'))

    def _progname(self):
        """Subcommand program name."""
        return "%s %s" % (os.path.basename(sys.argv[0]), self.command)

    def _parse_args(self, parser):
        """Parse subcommand arguments."""
        self.args = parser.parse_args(sys.argv[2:], self.args)
        global verbose
        global dryrun
        verbose = self.args.verbose
        dryrun = self.args.dryrun

    def _unknown(self):
        die('Unknown command: %s' % (self.command))

    def help(self):
        """Print usage string."""
        print('usage:', USAGE)
        print(DESC)

    def version(self):
        """Print version string."""
        print('virt-lab', VERSION)

    def create(self):
        """Create the virtual lab guests."""
        parser = argparse.ArgumentParser(
            prog=self._progname(),
            description=self.create.__doc__)
        parser.add_argument('name')
        parser.add_argument('-v', '--verbose', action='store_true')
        parser.add_argument('-n', '--dryrun', action='store_true')
        parser.add_argument('-c', '--config')
        for key in sorted(DEFAULTS.keys()):
            parser.add_argument('--'+key)
        self._parse_args(parser)

        lab = VirtLabValues(self.args.name, self.args)
        for guest in lab.guests():
            guest.create()
        if lab.postcreate:
            rc = run(lab.postcreate)
            if rc != 0:
                die('post-create command failed: %s; rc=%d' % (lab.postcreate, rc))

    def destroy(self):
        """Destroy the virtual lab guests."""
        parser = argparse.ArgumentParser(
            prog=self._progname(),
            description=self.destroy.__doc__)
        parser.add_argument('name')
        parser.add_argument('-v', '--verbose', action='store_true')
        parser.add_argument('-n', '--dryrun', action='store_true')
        parser.add_argument('-c', '--config')
        parser.add_argument('--purge', action='store_true')
        parser.add_argument('--images')
        self._parse_args(parser)

        lab = VirtLabValues(self.args.name, self.args)
        for guest in lab.guests():
            guest.destroy(self.args.purge)
        if lab.postdestroy:
            rc = run(lab.postdestroy)
            if rc != 0:
                die('post-destroy command failed: %s; rc=%d' % (lab.postdestroy, rc))

    def start(self):
        """Start the virtual lab guests."""
        parser = argparse.ArgumentParser(
            prog=self._progname(),
            description=self.start.__doc__)
        parser.add_argument('name')
        parser.add_argument('-v', '--verbose', action='store_true')
        parser.add_argument('-n', '--dryrun', action='store_true')
        self._parse_args(parser)

        lab = VirtLabValues(self.args.name, self.args)
        for guest in lab.guests():
            guest.domain_start()

    def stop(self):
        """Stop the virtual lab guests."""
        parser = argparse.ArgumentParser(
            prog=self._progname(),
            description=self.stop.__doc__)
        parser.add_argument('name')
        parser.add_argument('-v', '--verbose', action='store_true')
        parser.add_argument('-n', '--dryrun', action='store_true')
        self._parse_args(parser)

        lab = VirtLabValues(self.args.name, self.args)
        for guest in lab.guests():
            guest.domain_stop()

    def list(self):
        """List virtual labs."""
        parser = argparse.ArgumentParser(
            prog=self._progname(),
            description=self.list.__doc__)
        parser.add_argument('-c', '--config')
        parser.add_argument('-b', '--brief', action='store_true')
        self._parse_args(parser)

        config = ConfigParser()
        try:
            with open(self.args.config) as f:
                config.readfp(f)
        except IOError as e:
            die('Unable to read config file %s.\n%s' % (self.args.config, e))

        if self.args.brief:
            for section in config.sections():
                print(section)
        else:
            names = virsh('list', '--name', '--all').split()
            for section in config.sections():
                lab = VirtLabValues(section, self.args)
                desc = lab.desc if lab.desc else ''
                guests = [g.name for g in lab.guests()]
                active = 'yes' if set(names) & set(guests) else 'no'
                print('Name:', lab.name)
                print('Desc:', desc)
                print('Guests:', ', '.join(guests))
                print('Active:', active)
                print()


    def main(self):
        """Main return for virt-lab"""
        parser = argparse.ArgumentParser(
            prog=self._progname(),
            description=DESC,
            usage=USAGE)
        parser.add_argument('command', help='subcommand to run')
        args = parser.parse_args(sys.argv[1:2], self.args)
        self.command = args.command
        if self.command.startswith('_'):
            self.command = '_unknown'
        getattr(self, self.command, self._unknown)()


if __name__ == '__main__':
    VirtLab().main()
